use_frameworks!

target 'vaslAppSdk_Example' do
    
  pod 'vaslAppSdk', :path => '../'
  pod 'SwiftProtobuf'
  pod 'Alamofire' , '4.9.1'
  
  target 'vaslAppSdk_Tests' do
    inherit! :search_paths
    
  end
end
